### ISSUE TITLE
Start screen

### ISSUE THREAD

**Issue by electron2302** [brainkeeper/frontend#13]
As a user I need a start screen.
It should let me:
- start a Session
- go into settings 
- go to see my statistics
- go to the person editing page

Estimated: 5h

**Comment by electron2302** [comment]
The Person appointed to this task, should also clean up the “page” that we already have, and create a structure for the future Pages

**Comment by walli545** [comment]
### Tasks
- [ ]  Clean up app component
- [ ]  Create routes and components for new features
- [ ]  Create start screen
