### ISSUE TITLE
Theme colors and variables

### ISSUE THREAD

**Issue by electron2302** [brainkeeper/frontend#2]
As the user I want a consistent and visual pleasing color throughout the app

### Tasks:
- [x] Change primary color
- [x] Provide theme colors as scss variables

### Acceptance criteria:
- [ ] Less aggressive green as primary color
- [ ] Theme colors can be used in other scss files
