### ISSUE TITLE
Create, edit and delete persons

### ISSUE THREAD

**Issue by electron2302** [brainkeeper/frontend#25]
As a user I want to create, edit and delete persons.

This  should all be done over a single addition page, with the form elements, which will be empty if u create a new user, and will be pre populated if the user wants to change a person, also o this page should be buttons for deleting a user (if already exists) or to save the changes.

The changing of pictures does not need to be implemented, it will be its own issue

**Comment by walli545** [comment]
### Tasks
- [ ]  Create person editor component
- [ ]  Add routes for new person and existing person (with id)
- [ ]  Display properties of existing person
- [ ]  Form validation
- [ ]  Snackbar when changes were saved or something went wrong
- [ ] Confirm dialog when user wants to exit page but has unsaved changes
- [ ] Confirm dialog when user wants to delete a person
