### ISSUE TITLE
Set and change pictures of persons

### ISSUE THREAD

**Issue by electron2302** [brainkeeper/frontend#26]
As a user I want to set and change pictures of the persons either from a picture stored on the device or from a live camera.

I would guess that there already exists something in/for angular that only needs to be installed and then used correctly, I think we aren’t the first ones wanting to import images into an angular app

**Comment by walli545** [comment]
### Tasks

- [ ] Importing of pictures from storage
- [ ] Importing of pictures from camera (mobile)
- [ ] Use image conversion service from #12
