### ISSUE TITLE
Persons management service

### ISSUE THREAD

**Issue by walli545** [brainkeeper/frontend#8]
As a developer I want to have a service that manages persons available for the game.

### Tasks:
- [x] Interface definition
- [x] Get to know IndexDB
- [x] Implement Person class
- [x] Implement PersonService
- [x] Add score to persons

### Acceptance criteria:
- [ ] Persons are stored in IndexDB and persist after reloading the page
- [ ] Persons can be added/removed/updated/queried
- [ ] A list of six random persons can be queried
- [ ] A list of persons with a score greater than 0 in descending order by score can be queried
- [ ] Images are stored as a Base64 encoded string
- [ ] Unit tests
