### ISSUE TITLE
Session logic

### ISSUE THREAD

**Issue by electron2302** [brainkeeper/frontend#9]
As a developer I want a service that holds the logic for one session.
One session consists of multiple rounds
One round is one set of 6 “persons” and ends after clicking the right one

The session logic should:
- populate the screen with 6 “persons”
- randomly choose the “right” one, and update the name component of the session accordingly
- trigger the “false” animation of a person element, if it was touched, and was not the right one
- trigger the “right” animation if it was the right one and after displaying it, a new round should start
- it should keep track in which round it is

### Tasks:
* [x] Implement Session Service
* [x] Get six random persons from the Person Service
* [x] Choose the one to be found in this round
* [x] Check whether the selected person is the correct one
* [x] Provide the name of the correct person to the name component
* [x] Keep track of the current round

### Acceptance Criteria:
* [x] Session Service implemented
* [x] Unit Tests
* [x] Access to persons through a PersonService implementation
* [x] New Rounds with different persons can be started
* [x] Correct Person is not changed during a round
* [x] It can be queried, whether a selected person was the correct one
